variables:
   GIT_SUBMODULE_STRATEGY: recursive
   ORD_SOUMET_W: "10"
   ORD_SOUMET_C: "1"
   ORD_SOUMET_M: "4G"
   ORD_SOUMET_TMPFS: "1G"

.env:
   build:
      - echo "No specific environment"
   variables:
      ALLOW_FAILURE_ARCHS: ""

include:
   - project: 'RPN-SI/ci-admin'
     ref: dev
     file: '/ci/.gitlab-ci-config.yml'

deploy:staging:
   stage: deploy
   script:
      - ~/ci-admin-bundle/bin/ci-stage-ssm.sh libs ${CI_PROJECT_NAME} "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"

trigger:
   stage: trigger
   script:
      - curl -X POST -F token=${ECCI_TRIGGER_FSTTOOLS}  -F ref=${ECCI_VERSION_FSTTOOLS} -F variables[EC_TRIGGER]=${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF} -F variables[ECCI_PROCESS]=${ECCI_PROCESS} https://gitlab.science.gc.ca/api/v4/projects/6032/trigger/pipeline
